version: '3.9'

services:
  aiops_app:
    build: .
    container_name: aiops_app
    ports:
      - "8080:8080"
    depends_on:
      - mimir

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - "8081:8081"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
